spring:
  config:
    activate:
      on-profile: tests
  datasource:
    url: jdbc:h2:file:./db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: create

  liqubase:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: devs

  datasource:
    url: jdbc:postgresql://localhost:5432/messages
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  h2:
    console:
      enabled: false

  liquibase:
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
